import Head from "next/head";
import Image from "next/image";
import styles from "../styles/style.module.scss";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import TimeLine from "@/components/Timeline";
import Post from "@/components/Post";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.container}>
        <TimeLine />
        <Post />
      </main>
      <Footer />
    </>
  );
}
